import chalk from 'chalk'
import inquirer from 'inquirer'
import os from 'node:os'
import crypto from 'node:crypto'
import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

const TELEGRAF_CONFIG_PATH = '/etc/telegraf/telegraf.conf'

type TigStackAnswers = {
  hostname: string
  telegrafDb: string
  telegrafUser: string
  telegrafPassword: string
  metricsDb: string
  metricsUser: string
  metricsPassword: string
  grafanaPassword: string
}

type LsbRelease = {
  distribId: string
  codename: string
}

const createPassword = () => {
  return crypto.randomBytes(12).toString('base64url').slice(0, 18)
}

const readLsbRelease = (): LsbRelease => {
  try {
    const contents = readFileSync('/etc/lsb-release', 'utf8')
    const data = contents
      .split('\n')
      .filter(Boolean)
      .reduce<Record<string, string>>((acc, line) => {
        const [key, rawValue] = line.split('=')
        if (key && rawValue) {
          acc[key.trim()] = rawValue.trim().replace(/"/g, '')
        }
        return acc
      }, {})
    return {
      distribId: data.DISTRIB_ID?.toLowerCase() || 'ubuntu',
      codename: data.DISTRIB_CODENAME || 'focal',
    }
  } catch (error) {
    return {
      distribId: 'ubuntu',
      codename: 'focal',
    }
  }
}

const runStep = (title: string, command: string, options?: { silent?: boolean }) => {
  console.log(chalk.cyan(`➜ ${title}`))
  const result = spawnSync(command, {
    shell: true,
    stdio: options?.silent ? 'ignore' : 'inherit',
  })
  if (result.status !== 0) {
    throw new Error(`${title} failed`)
  }
}

const sanitizeIdentifier = (value: string, field: string) => {
  if (!value || !/^[a-zA-Z0-9_\-]+$/.test(value)) {
    throw new Error(`${field} can only contain letters, numbers, "-", or "_"`)
  }
}

const configureTelegraf = (answers: TigStackAnswers) => {
  const backupPath = `${TELEGRAF_CONFIG_PATH}.${Date.now()}.bak`
  runStep(
    'Backing up existing telegraf config (if present)',
    `if [ -f ${TELEGRAF_CONFIG_PATH} ]; then sudo cp ${TELEGRAF_CONFIG_PATH} ${backupPath}; fi`,
  )
  const body = `# Generated by solc
[agent]
  hostname = "${answers.hostname}"
  flush_interval = "15s"
  interval = "15s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

[[inputs.mem]]
[[inputs.net]]
[[inputs.system]]
[[inputs.swap]]
[[inputs.netstat]]
[[inputs.processes]]
[[inputs.kernel]]
[[inputs.diskio]]

[[outputs.influxdb]]
  database = "${answers.telegrafDb}"
  urls = ["http://127.0.0.1:8086"]
  username = "${answers.telegrafUser}"
  password = "${answers.telegrafPassword}"
`
  const writeResult = spawnSync(`sudo tee ${TELEGRAF_CONFIG_PATH}`, {
    shell: true,
    stdio: ['pipe', 'inherit', 'inherit'],
    input: body,
  })
  if (writeResult.status !== 0) {
    throw new Error('Writing telegraf config failed')
  }
}

const configureInfluxDb = (answers: TigStackAnswers) => {
  const statements = [
    `create database ${answers.telegrafDb}`,
    `create user ${answers.telegrafUser} with password '${answers.telegrafPassword}'`,
    `grant all on ${answers.telegrafDb} to ${answers.telegrafUser}`,
    `create database ${answers.metricsDb}`,
    `create user ${answers.metricsUser} with password '${answers.metricsPassword}'`,
    `grant write on ${answers.metricsDb} to ${answers.metricsUser}`,
    `grant all on ${answers.metricsDb} to ${answers.telegrafUser}`,
  ]
  statements.forEach((statement) => {
    const escaped = statement.replace(/"/g, '\\"')
    runStep(`InfluxDB: ${statement}`, `sudo influx -execute "${escaped}"`)
  })
}

export const installTigStack = async () => {
  if (process.platform !== 'linux') {
    console.log(chalk.red('TIG stack installation is only supported on Linux hosts.'))
    return
  }

  const defaults: TigStackAnswers = {
    hostname: os.hostname(),
    telegrafDb: 'telegraf',
    telegrafUser: 'telegraf',
    telegrafPassword: createPassword(),
    metricsDb: 'metricsdb',
    metricsUser: 'metrics',
    metricsPassword: createPassword(),
    grafanaPassword: createPassword(),
  }

  const answers = await inquirer.prompt<TigStackAnswers>([
    {
      name: 'hostname',
      message: 'Hostname to display on Grafana dashboards',
      type: 'input',
      default: defaults.hostname,
    },
    {
      name: 'telegrafDb',
      message: 'InfluxDB database for local system metrics',
      type: 'input',
      default: defaults.telegrafDb,
    },
    {
      name: 'telegrafUser',
      message: 'InfluxDB user for the Telegraf agent',
      type: 'input',
      default: defaults.telegrafUser,
    },
    {
      name: 'telegrafPassword',
      message: 'Password for the Telegraf InfluxDB user',
      type: 'password',
      mask: '*',
      default: defaults.telegrafPassword,
    },
    {
      name: 'metricsDb',
      message: 'InfluxDB database to receive validator metrics',
      type: 'input',
      default: defaults.metricsDb,
    },
    {
      name: 'metricsUser',
      message: 'InfluxDB user for remote validators',
      type: 'input',
      default: defaults.metricsUser,
    },
    {
      name: 'metricsPassword',
      message: 'Password for the validator InfluxDB user',
      type: 'password',
      mask: '*',
      default: defaults.metricsPassword,
    },
    {
      name: 'grafanaPassword',
      message: 'Grafana admin password',
      type: 'password',
      mask: '*',
      default: defaults.grafanaPassword,
    },
  ])

  sanitizeIdentifier(answers.telegrafDb, 'Telegraf database')
  sanitizeIdentifier(answers.metricsDb, 'Metrics database')
  sanitizeIdentifier(answers.telegrafUser, 'Telegraf user')
  sanitizeIdentifier(answers.metricsUser, 'Metrics user')

  const release = readLsbRelease()

  console.log(chalk.white('📈 Installing Solana monitoring TIG stack...'))

  runStep('Updating apt cache', 'sudo apt-get update -y')
  runStep(
    'Installing prerequisite packages',
    'sudo apt-get install -y gnupg2 software-properties-common wget curl apt-transport-https',
  )
  runStep(
    'Adding InfluxData GPG key',
    'wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -',
  )
  runStep(
    'Adding InfluxData apt repository',
    `echo "deb https://repos.influxdata.com/${release.distribId} ${release.codename} stable" | sudo tee /etc/apt/sources.list.d/influxdata.list > /dev/null`,
  )
  runStep('Refreshing apt cache (InfluxData)', 'sudo apt-get update -y')
  runStep('Installing Telegraf', 'sudo apt-get install -y telegraf')
  runStep('Enabling Telegraf service', 'sudo systemctl enable --now telegraf')
  runStep('Installing InfluxDB', 'sudo apt-get install -y influxdb')
  runStep('Enabling InfluxDB service', 'sudo systemctl enable --now influxdb')
  runStep(
    'Adding Grafana GPG key',
    'wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -',
  )
  runStep(
    'Adding Grafana apt repository',
    'sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main" -y',
  )
  runStep('Installing Grafana', 'sudo apt-get update -y && sudo apt-get install -y grafana')
  runStep('Enabling Grafana service', 'sudo systemctl daemon-reload && sudo systemctl enable --now grafana-server')

  configureTelegraf(answers)
  configureInfluxDb(answers)

  runStep('Restarting Telegraf', 'sudo systemctl restart telegraf')
  runStep('Restarting InfluxDB', 'sudo systemctl restart influxdb')
  runStep(
    'Resetting Grafana admin password',
    `sudo grafana-cli admin reset-admin-password '${answers.grafanaPassword}'`,
  )

  console.log(chalk.green('\n✅ TIG stack installation complete'))
  console.log(chalk.white('\nInfluxDB details:'))
  console.log(`  • Local metrics DB: ${answers.telegrafDb}`)
  console.log(`    user: ${answers.telegrafUser}`)
  console.log(`    password: ${answers.telegrafPassword}`)
  console.log(`  • Validator metrics DB: ${answers.metricsDb}`)
  console.log(`    user: ${answers.metricsUser}`)
  console.log(`    password: ${answers.metricsPassword}`)
  console.log(chalk.white('\nGrafana:'))
  console.log('  • URL: http://<server-ip>:3000')
  console.log(`  • admin password: ${answers.grafanaPassword}`)
  console.log(chalk.white('\nNext steps:'))
  console.log(
    '  • Configure your validator telegraf/monitor.sh to POST to http://<server-ip>:8086 using the metrics user above.',
  )
}
